### ISSUE TITLE
helperfile.py issues

### ISSUE THREAD

**Issue by LastAncientOne** [knathanieltucker/209fp#1]
I put all the file that is require in the lib, but I cannot use helperfile.
I put data_panel in the lib too.

TypeError                                 Traceback (most recent call last)
<ipython-input-40-8700ebdfaa41> in <module>()
----> 1 import helperfile

C:\Users\LastAncientOne\AppData\Local\Enthought\Canopy32\User\lib\site-packages\helperfile.py in <module>()
     40 plt.rc('figure', figsize=(10, 6))
     41 np.random.seed(123456)
---> 42 panel = Panel.load('data_panel')
     43 close_px = panel['Adj Close']
     44 RR = close_px / close_px.shift(1) - 1

TypeError: unbound method load() must be called with Panel instance as first argument (got str instance instead) 

Can you help me with this issues please.

**Comment by siegel14159265** [comment]
what's this nate?

On 17 January 2015 at 19:33, LastAncientOne notifications@github.com
wrote:

> I put all the file that is require in the lib, but I cannot use helperfile.
> I put data_panel in the lib too.
> 
> TypeError Traceback (most recent call last)
> in ()
> ----> 1 import helperfile
> 
> C:\Users\LastAncientOne\AppData\Local\Enthought\Canopy32\User\lib\site-packages\helperfile.py
> in ()
> 40 plt.rc('figure', figsize=(10, 6))
> 41 np.random.seed(123456)
> ---> 42 panel = Panel.load('data_panel')
> 43 close_px = panel['Adj Close']
> 44 RR = close_px / close_px.shift(1) - 1
> 
> TypeError: unbound method load() must be called with Panel instance as
> first argument (got str instance instead)
> 
> Can you help me with this issues please.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/knathanieltucker/209fp/issues/1.

## 

Chris Dantzlerward
Harvard University '13

**Comment by LastAncientOne** [comment]
Why I cannot use the helper file? I cannot import it... when I am using ipython or idle. Please can someone help. I appreciate it.

**Comment by siegel14159265** [comment]
who are you?

On 21 January 2015 at 20:17, LastAncientOne notifications@github.com
wrote:

> Why I cannot use the helper file? I cannot import it... when I am using
> ipython or idle. Please can someone help. I appreciate it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/knathanieltucker/209fp/issues/1#issuecomment-70955057
> .

## 

Chris Dantzlerward
Harvard University '13

**Comment by LastAncientOne** [comment]
I am student and learning how to use python and I am interesting in your codes.
